project_id = "tempcontrol"
[auth]
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["http://localhost:5173", "http://127.0.0.1:5173"]
minimum_password_length = 8
[auth.email]
enable_signup = true
enable_confirmations = true
